title: "BotSauce"
remote_theme: pmarsceill/just-the-docs
heading_anchors: true
color_scheme: dark
footer_content: [Source code on GitHub](https://www.github.com/BotSauce/BotSauce){: .btn .btn-purple .mr-2 } [Vsauce3 Discord Server](https://discord.gg/VRr4hVR){: .btn .btn-blue }
