title: "BotSauce"
remote_theme: pmarsceill/just-the-docs


# Aux links for the upper right navigation
aux_links:
  "Status":
    - "https://botsauce.github.io/status/"
  "Source code":
    - "//github.com/BotSauce/BotSauce"
  "Vsauce3 Discord Server":
    - "https://discord.gg/CxAbq5U"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Display the relative url in search results
# Supports true (default) or false
search.rel_url: false

# Footer content 
# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 <a href=\"https://github.com/Montelion\">Monty#3581</a>. Distributed under a <a href=\"https://github.com/BotSauce/botsauce.github.io/blob/master/LICENSE\">GPL-3.0 License</a>. <a href=\"https://github.com/BotSauce/botsauce.github.io\">Website source code</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
